### ISSUE TITLE
Information missing in settings page

### ISSUE THREAD

**Issue by syberjedi1999** [bitfocus/companion-module-teradek-vidiu#3]
In the settings page for this module in companion, there is no mention that a password is REQUIRED. I used to get Javascript errors when loading companion until I realized they went away when I disabled this module. Could never get it to work until I decided to set a password in my Vidiu Pro. As soon as I enabled and updated the module, no issue starting or stopping the stream. 

It would be helpful to just include a comment about a password being required to work, and/or a way to make it work without a password. 

Thanks!

**Comment by krocheck** [comment]
Yeah, there isn't a catch for that field being undefined.  I'll get that cleaned up in the next day or so.

**Comment by josephdadams** [comment]
I added some error handling for this. :)
