### ISSUE TITLE
Issue/Compatibility with VidiU Go

### ISSUE THREAD

**Issue by ThatGuySittin** [bitfocus/companion-module-teradek-vidiu#5]
I have recently purchased a vidiu go, and unfortunately this module does not seem to work with the broadcast function specifically. When I use the record function, in record mode, it works great. But the “start broadcast” function Causes JS errors and crashes Companion. Does anyone know of this issue?

**Comment by josephdadams** [comment]
I wrote this module. Can you share a screenshot of the error message?

**Comment by ThatGuySittin** [comment]
@josephdadams I will. Unfortunately right now I’m
Out of state but I will as soon as I get back this weekend! Thanks for reaching out

**Comment by josephdadams** [comment]
@ThatGuySittin are you still getting this error?

**Comment by ThatGuySittin** [comment]
> @ThatGuySittin are you still getting this error?

I have not honestly been able to get back over there to check. We started just using the front interface, and so I am not sure! I will have it checked this weekend to see! Thank you for following up.

**Comment by josephdadams** [comment]
I’m here to help if I can! This module simulates the web interface in order to authenticate and run the functions, so it’s possible that some proper debugging against your device may be needed.

**Comment by syberjedi1999** [comment]
I just switched to the Go and have had the same problem. I'll "crash" companion to get you a screen grab. :-D

**Comment by josephdadams** [comment]
Thanks! The fixes I pushed today were not hot fixes, they will have to be merged with the core and a new build generated before you have access to them.

**Comment by MattGrover** [comment]
I tried the VidiU instance yesterday with my VidiU Go, put the IP address in (no password set), applied and it crashed Companion (Houston we have a problem page in Chrome and the app quit itself), couldn't get it restarted to remove the instance until I pulled the ethernet from the VidiU.

Haven't tried it again today yet as I'm live with a show soon

Windows 10, Companion v2.1.2 (2.1.2-f4bcaf3-2679), VidiU Go Firmware 3.1.12r35105

**Comment by RoseOO** [comment]
@MattGrover I don't think this has ever been properly tested on a VidiU Go. If you could include in your companion log file after a crash that would be helpful. It looks like the fixes done for this issue were never tested.

**Comment by MattGrover** [comment]
> @MattGrover I don't think this has ever been properly tested on a VidiU Go. If you could include in your companion log file after a crash that would be helpful. It looks like the fixes done for this issue were never tested.

Happy to upload a log file, where would I find it..?

**Comment by RoseOO** [comment]
I'm not sure where Companion installs on Windows. So maybe someone else can chime in there?

**Comment by RoseOO** [comment]
@MattGrover Just found out you will the companion.log file in:

`%appdata%/Companion`
