### ISSUE TITLE
Vidiu X Compatibility

### ISSUE THREAD

**Issue by phelfenbein** [bitfocus/companion-module-teradek-vidiu#8]
Teradek released the Vidiu X earlier this year.  Apparently they changed their API; the current Vidiu module doesn't work with it.  Do you need to wait for Teradek to finish API documentation for the X before it can ben incorporated into Companion or is there a way I can help get basic functionality working?  As of four months ago Teradek is working on API documentation for the X (and Prism).

**Comment by josephdadams** [comment]
When I wrote the Vidiu module, they didn’t even have an API. I reverse engineered their web UI to emulate a connection and make it work. So it doesn’t surprise me at all that it doesn’t work with a new model.

**Comment by RoseOO** [comment]
The following models are not going to be supported in the new API

Unsupported:

Beam
Bolt
Clip
Link (2017 model) and Link Pro
Sphere
VidiU (original), VidiU Mini

There is a bit more info here:
https://support.teradek.com/hc/en-us/articles/222921208-Is-there-a-public-API-for-working-with-Teradek-encoders-or-decoders-

It will be a rewrite to support the new models.

**Comment by phelfenbein** [comment]
I would think it'd be easier to rewrite if it's a REST-based API.  I wonder if the app uses the REST API or something else.  I could try to do a packet capture, maybe it'll be easier to reverse-engineer.  
Interestingly it doesn't prompt for the password if the password is left at the default.  If not there's a password prompt.

**Comment by josephdadams** [comment]
I had someone ask to hire me to write a Vidiu X module, so I've just finished reverse engineering what it would take to trigger both recording and broadcasting. I've sent him the quote to create it, so if we move forward, I can update you here when that module is available.

**Comment by phelfenbein** [comment]
I'd appreciate knowing when it's available.  If he declines I'd be interested in knowing the next steps / other options.  Thanks

**Comment by josephdadams** [comment]
I'll update you either way. Thanks!

**Comment by josephdadams** [comment]
@phelfenbein the other person isn’t ready to move forward at this time. So if you’d like to discuss it, shoot me an email. My email address is listed in my github profile. I can’t list it here or it will get filtered. Thanks!

**Comment by josephdadams** [comment]
The VidiU X module is now available in the beta builds and the repo is here: https://github.com/bitfocus/companion-module-teradek-vidiux

I made a new repo because the codebase is quite different.

Huge thanks to @phelfenbein for sponsoring me to finish this module out.
